### PR TITLE
Leo webpack

### PR DESCRIPTION
**Pull request by dwido**
@sagivf @tsachis @MrFrankel @danrevah 

speak now or forever hold your peace

### CODE REVIEW

**Comment by sagivf** [comment]
@dwido Haven't had time to check it yet. Hopefully tomorrow.
But you can go ahead and merge if it works.

**Comment by dwido** [comment]
@sagivf I made all the changes that were left, so now it's fuller, i ran amplifyapp against this version, so we should be good :)

**Comment by sagivf** [comment]
@dwido This is awesome! super fast development.
I tried it agains my [rjq-ui](https://sagivf.github.io/rjq-ui) project and it worked perfectly,
using global script, import or require - all worked 🎉 

There are however two issues in the angularIL development environment (it does run tough):
1)
Getting these weird error.
image

2)
Not sure it's related to this change or the above error, but the recorder doesn't work if the mocking is off, strange...

**Comment by dwido** [comment]
@sagivf I haven't seen this error, how did you get it? can you send steps to reproduce?

**Comment by sagivf** [comment]
Just checkout your branch and did `npm run start` I'll try to reinstall stuff but it's weird that errors are coming from non related files.

**Comment by sagivf** [comment]
@dwido reinstalling the bower components in angularIL removes the errors. We need to check why webpack is looking there... Issue 2 is still there.

**Comment by sagivf** [comment]
@dwido l once we merge this I will work on the docs.
Is there any reason not to? I think is works nicely

**Comment by dwido** [comment]
!go for it

**Comment by Incognito** [comment]
Thanks for this patch, it this tool makes my development easier and I'm able to integrate it with my webpack build now.

If you're working on docs, this may be useful to you. I'm using webpack 1.13 at the moment and here's what I had to change to get this working:

```
--- a/package.json
+++ b/package.json
     "image-webpack-loader": "^3.3.0",
-    "normalize.css": "^3.0.3"
+    "leonardojs": "^3.1.8",
+    "normalize.css": "^3.0.3",
+    "script-loader": "^0.7.0"
   },
   "devDependencies": {
     "angular-mocks": "^1.5.0",
diff --git a/webpack.config.js b/webpack.config.js
index 8027261..5b11f20 100644
--- a/webpack.dev.config.js
+++ b/webpack.dev.config.js
@@ -4,13 +4,16 @@ var HtmlWebpackPlugin = require('html-webpack-plugin');
 
 module.exports = {
   devtool: 'source-map',
-  entry: {},
+  entry: {
+    mock: './mock.js'
+  },
   module: {
     loaders: [
       { test: /\.css$/, loader: 'style!css' },
+      { test: /\/leonardo.js/, loader: 'script-loader' },
       {
```
I'm leaving this here in the event someone else needs to discover how to do this, or you'd like to include this in your documentation.

**Comment by sagivf** [comment]
Thanks @Incognito, we hope this tool can help you out. We use it on a number of projects and it helps us out a lot. Were trying to make it as friendly as possible to accommodate the different (and changing) environments and use cases. We'd be thrilled to hear what works and what doesn't...

Regarding the docs. You are absolutely right - i've got an issue on it - https://github.com/outbrain/Leonardo/issues/152. I'll be working on it soon.

**Pull request merged**
